name: YBVWelcome
version: '1.1'
main: org.yabogvk.ybvwelcome.YBVWelcome
api-version: '1.21'
author: yabogvk
website: https://github.com/sokolovskiyoleg
description: Настрой сообщения о входе/выходе
softdepend: ["PlaceholderAPI"]

commands:
  ybvwelcome:
    usage: /<command> [set|clear|reload]
    aliases: [welcome]
    permission: ybvwelcome.use
permissions:
  ybvwelcome.use:
    description: Доступ к базовой команде
    default: op
  ybvwelcome.set:
    description: Возможность устанавливать свои сообщения входа/выхода
    default: op
  ybvwelcome.admin:
    description: Доступ к перезагрузке плагина
    default: op